version: '3.8'

services:
  api:
    build: ./back_end_API
    container_name: express-api
    ports:
      - "3000:3000"
    networks:
      - app-network

  web:
    build: ./front_end
    container_name: vite-web
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge